org: nelsoncode019
app: my-lambda
service: my-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux